## Deployment playbook goes here.
---
- name: Copy backend files
  become: true
  copy:
      src: /home/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz

- name: Start PM2
  shell: |
      cd /home/ubuntu/
      tar xzvf artifact.tar.gz
      npm install
      pm2 stop default
      pm2 start npm --start