## Deployment playbook goes here.
---
- name: create backend directory
  become: yes
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Copy backend files
  become: yes
  copy:
      src: ~/project/artifact.tar.gz
      dest: ~/backend/artifact.tar.gz


- name: unpack backend files
  become: yes
  shell: |
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz
  args:
    chdir: /root/backend

- name: Start PM2
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
